services:
  app:
    build: .
    image: app_image # Add an image name for better consistency
    ports:
      - 3000 # Expose port 3000, Nginx will balance between the instances internally
    deploy:
      replicas: 2  # Spin up 2 instances of the app service automatically
      restart_policy:
        condition: on-failure  # Restart instances if they crash
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"  # Expose port 80 for the load balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Use the custom Nginx configuration
    networks:
      - app-network

networks:
  app-network:
    driver: bridge